version: '3.8'
services:
  techblog:
    image: techblog
    build: .
    environment:
      - DEVELOPMENT=true
    volumes:
      - db:/app/db

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
    depends_on:
      - techblog

volumes:
  db:
